/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIntroducingOspreyRouteImport } from './routes/blog.introducing-osprey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIntroducingOspreyRoute = BlogIntroducingOspreyRouteImport.update({
  id: '/blog/introducing-osprey',
  path: '/blog/introducing-osprey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/introducing-osprey': typeof BlogIntroducingOspreyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/introducing-osprey': typeof BlogIntroducingOspreyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/introducing-osprey': typeof BlogIntroducingOspreyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog/introducing-osprey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/introducing-osprey'
  id: '__root__' | '/' | '/blog/introducing-osprey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogIntroducingOspreyRoute: typeof BlogIntroducingOspreyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/introducing-osprey': {
      id: '/blog/introducing-osprey'
      path: '/blog/introducing-osprey'
      fullPath: '/blog/introducing-osprey'
      preLoaderRoute: typeof BlogIntroducingOspreyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogIntroducingOspreyRoute: BlogIntroducingOspreyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
